### 
GET http://localhost:3000/notenlogqv/getall HTTP/1.1

### 
GET http://localhost:3000/notenlogqv/detail/M187 HTTP/1.1

### 
GET http://localhost:3000/notenlogqv/template HTTP/1.1

### 
POST http://localhost:3000/notenlogqv/addone HTTP/1.1
content-type: application/json

{
    "name": "M122",
    "data": {
        "ModulNummer": "",
        "ModulTitel": "",
        "ModulTyp": "",
        "Note": "",
        "Erreichungsgrad": [],
        "Handlungsziele": [
            {
                "Nummer": "",
                "Beschreibung": ""
            }
        ]
    }
}

###########################################################
